repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v6.8.0"
    hooks:
      - id: eslint
        name: Lint JS/TS code and JSON files
        description: Run ESLint agains all JS/TS/JSON files
        files: \.([jt]sx?|jsonc?)$
        types: [file]
        args: ["--fix", "--ignore-pattern", "!**/.*.js"]
        additional_dependencies:
          - "@vue/eslint-config-prettier@6.0.0"
          - "babel-eslint@10.1.0"
          - "eslint@6.8.0"
          - "eslint-config-airbnb-base@14.2.0"
          - "eslint-plugin-import@2.20.2"
          - "eslint-plugin-json-format@2.0.1"
          - "eslint-plugin-prettier@3.1.4"
          - "eslint-plugin-vue@6.2.2"
          - "prettier@2.0.5"
